// "use client"
import sty from "./blog.module.css";
import PostCard from "@/components/PostCard/PostCard";
import { getPosts } from "@/libs/services";

export const metadata = {
  title: "Blog page",
  description: "Generated by create next app",
};

// FETCH DATA WITH API
const getApiPost = async () => {
  const res = await fetch("http://localhost:3000/api/blog");

  if (!res.ok) throw new Error("nigga aint working");

  return res.json();
};

export default async function BlogPage() {
  // fetch data without api
  // const posts = await getPosts()

  const posts = await getApiPost();

  return (
    <>
      <div className={sty.container}>
        {posts?.map((post) => (
          <div className={sty.post} key={post.slug}>
            <PostCard post={post} />
          </div>
        ))}
      </div>
    </>
  );
}
